on:
  release:
  push:

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Trigger dispatch for external repo
        run: |
          curl -X POST --header 'authorization: Bearer ${{ secrets.HELICS_BOT_TOKEN }}' \
          --url https://api.github.com/repos/GMLC-TDC/helics-packaging/dispatches \
          --header 'content-type: application/json' \
          --data '{"event_type":"helics-version-update","client_payload":{"repository":"test_repo","tag_name":"v2.4.1","version":"2.6.0"}}'
      - name: Trigger dispatch
        run: |
          curl -X POST --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --url https://api.github.com/repos/nightlark/test-action-dispatch-comment/dispatches \
          --header 'content-type: application/json' \
          --data '{"event_type":"test-dispatch","client_payload":{"test_field":"my first field"}}'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
